//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTam.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANG_GIA_HOC_PHI
    {
        public System.Guid MA_KHOI { get; set; }
        public System.Guid MA_MON { get; set; }
        public System.Guid MA_LOAI { get; set; }
        public Nullable<decimal> DON_GIA { get; set; }
        public Nullable<double> SO_BUOI { get; set; }
    
        public virtual KHOI_LOP KHOI_LOP { get; set; }
        public virtual LOAI_LOP LOAI_LOP { get; set; }
        public virtual MON_HOC MON_HOC { get; set; }
    }
}
