//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTam.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUOI_HOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BUOI_HOC()
        {
            this.CT_BUOIHOC = new HashSet<CT_BUOIHOC>();
            this.HOA_DON = new HashSet<HOA_DON>();
        }
    
        public System.Guid MA_BUOI { get; set; }
        public string TEN_BUOI { get; set; }
        public Nullable<bool> DIEM_DANH_GV { get; set; }
        public Nullable<int> SI_SO_THUC { get; set; }
        public Nullable<System.Guid> MA_LUONG { get; set; }
        public Nullable<System.Guid> MA_LOP { get; set; }
    
        public virtual BANG_LUONG BANG_LUONG { get; set; }
        public virtual LOP_HOC LOP_HOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_BUOIHOC> CT_BUOIHOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
    }
}
