//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTam.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIEU_NGOAI
    {
        public System.Guid MA_CT { get; set; }
        public string TEN_CT { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public Nullable<double> THANH_TIEN { get; set; }
    }
}
