//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTam.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONG_NO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONG_NO()
        {
            this.CT_CONG_NO = new HashSet<CT_CONG_NO>();
        }
    
        public System.Guid MA_CONG_NO { get; set; }
        public string TEN_CONG_NO { get; set; }
        public Nullable<decimal> TONG_TIEN { get; set; }
        public Nullable<System.DateTime> NGAY_THANH_TOAN { get; set; }
        public System.DateTime NGAY_LAP_CONG_NO { get; set; }
        public string MA_HS { get; set; }
        public Nullable<System.Guid> MA_KM { get; set; }
        public bool TRANG_THAI { get; set; }
    
        public virtual HOC_SINH HOC_SINH { get; set; }
        public virtual KHUYEN_MAI KHUYEN_MAI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_CONG_NO> CT_CONG_NO { get; set; }
    }
}
