//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTam.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_HOADON
    {
        public System.Guid MA_HD { get; set; }
        public System.Guid MA_BUOI { get; set; }
        public Nullable<double> LUONG { get; set; }
    
        public virtual BUOI_HOC BUOI_HOC { get; set; }
        public virtual HOA_DON HOA_DON { get; set; }
    }
}
