//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTam.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_LOP_HOC
    {
        public System.Guid MA_LOP { get; set; }
        public string MA_HS { get; set; }
        public Nullable<System.DateTime> NGAY_VAO_HOC { get; set; }
    
        public virtual HOC_SINH HOC_SINH { get; set; }
        public virtual LOP_HOC LOP_HOC { get; set; }
    }
}
