//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTam.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANH_GIA_CUOI_THANG
    {
        public System.Guid MA_DG { get; set; }
        public string NHAN_XET { get; set; }
        public string CHUYEN_CAN { get; set; }
        public Nullable<System.DateTime> NGAY_LAP { get; set; }
        public Nullable<System.Guid> MA_LOP { get; set; }
        public string MA_HS { get; set; }
        public Nullable<double> DIEM_TB { get; set; }
    
        public virtual HOC_SINH HOC_SINH { get; set; }
        public virtual LOP_HOC LOP_HOC { get; set; }
    }
}
