//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTam.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GHI_DANH
    {
        public System.Guid MA_TB { get; set; }
        public string HO_TEN { get; set; }
        public Nullable<System.DateTime> NG_SINH { get; set; }
        public string SDT { get; set; }
        public string DIA_CHI { get; set; }
        public string TRUONG { get; set; }
        public string NOI_DUNG { get; set; }
        public Nullable<bool> TINH_TRANG { get; set; }
    }
}
