//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTam.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIA_SU
    {
        public System.Guid MA_GIA_SU { get; set; }
        public string TEN_LOP { get; set; }
        public string DON_GIA { get; set; }
        public string DIA_CHI { get; set; }
        public string MON_DAY { get; set; }
        public string THOI_GIAN { get; set; }
        public string YEU_CAU { get; set; }
        public string LIEN_HE { get; set; }
    }
}
