//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTam.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAO_VIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIAO_VIEN()
        {
            this.BUOI_HOC = new HashSet<BUOI_HOC>();
            this.HOA_DON = new HashSet<HOA_DON>();
            this.LOP_HOC = new HashSet<LOP_HOC>();
            this.NGOAI_GIO = new HashSet<NGOAI_GIO>();
        }
    
        public string MA_GV { get; set; }
        public string HO_TEN { get; set; }
        public string SDT { get; set; }
        public string GIOI_TINH { get; set; }
        public string EMAIL { get; set; }
        public bool TRANG_THAI { get; set; }
        public Nullable<System.DateTime> NG_SINH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUOI_HOC> BUOI_HOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP_HOC> LOP_HOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGOAI_GIO> NGOAI_GIO { get; set; }
    }
}
