//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTam.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOC_SINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOC_SINH()
        {
            this.CONG_NO = new HashSet<CONG_NO>();
            this.CT_BUOIHOC = new HashSet<CT_BUOIHOC>();
            this.CT_LOP_HOC = new HashSet<CT_LOP_HOC>();
            this.DANH_GIA_CUOI_THANG = new HashSet<DANH_GIA_CUOI_THANG>();
        }
    
        public string MA_HS { get; set; }
        public string HO_TEN { get; set; }
        public System.DateTime NG_SINH { get; set; }
        public string GIOI_TINH { get; set; }
        public Nullable<int> KHOI { get; set; }
        public string TRUONG { get; set; }
        public string SDT { get; set; }
        public string DIA_CHI { get; set; }
        public string SDT_PH { get; set; }
        public Nullable<System.DateTime> NG_VAO_HOC { get; set; }
        public string PHU_HUYNH { get; set; }
        public Nullable<bool> TINH_TRANG { get; set; }
        public string MON_DK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONG_NO> CONG_NO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_BUOIHOC> CT_BUOIHOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_LOP_HOC> CT_LOP_HOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANH_GIA_CUOI_THANG> DANH_GIA_CUOI_THANG { get; set; }
    }
}
