//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTam.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOC_SINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOC_SINH()
        {
            this.CONG_NO = new HashSet<CONG_NO>();
            this.CT_BUOIHOC = new HashSet<CT_BUOIHOC>();
            this.LOP_HOC = new HashSet<LOP_HOC>();
        }
    
        public string MA_HS { get; set; }
        public string HO_TEN { get; set; }
        public string KHOI { get; set; }
        public string TRUONG { get; set; }
        public string SDT { get; set; }
        public string PHU_HUYNH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONG_NO> CONG_NO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_BUOIHOC> CT_BUOIHOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP_HOC> LOP_HOC { get; set; }
        public virtual TAI_KHOAN TAI_KHOAN { get; set; }
    }
}
