//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTam.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP_HOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOP_HOC()
        {
            this.BUOI_HOC = new HashSet<BUOI_HOC>();
            this.CT_CONG_NO = new HashSet<CT_CONG_NO>();
            this.CT_LOP_HOC = new HashSet<CT_LOP_HOC>();
            this.DANH_GIA_CUOI_THANG = new HashSet<DANH_GIA_CUOI_THANG>();
            this.THOI_KHOA_BIEU = new HashSet<THOI_KHOA_BIEU>();
        }
    
        public System.Guid MA_LOP { get; set; }
        public string TEN_LOP { get; set; }
        public Nullable<int> SI_SO { get; set; }
        public Nullable<System.DateTime> NGAY_AP_DUNG { get; set; }
        public string MA_GV { get; set; }
        public Nullable<System.DateTime> NGAY_KET_THUC { get; set; }
        public Nullable<System.DateTime> NGAY_BAT_DAU { get; set; }
        public Nullable<short> TRANG_THAI { get; set; }
        public Nullable<System.DateTime> NGAY_MO_LOP { get; set; }
    
        public virtual BANG_GIA_HOC_PHI BANG_GIA_HOC_PHI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUOI_HOC> BUOI_HOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_CONG_NO> CT_CONG_NO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_LOP_HOC> CT_LOP_HOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANH_GIA_CUOI_THANG> DANH_GIA_CUOI_THANG { get; set; }
        public virtual GIAO_VIEN GIAO_VIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THOI_KHOA_BIEU> THOI_KHOA_BIEU { get; set; }
    }
}
