//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTam.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP_HOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOP_HOC()
        {
            this.BUOI_HOC = new HashSet<BUOI_HOC>();
            this.THOI_KHOA_BIEU = new HashSet<THOI_KHOA_BIEU>();
            this.CONG_NO = new HashSet<CONG_NO>();
            this.HOC_SINH = new HashSet<HOC_SINH>();
        }
    
        public System.Guid MA_LOP { get; set; }
        public string TEN_LOP { get; set; }
        public Nullable<int> SI_SO { get; set; }
        public Nullable<System.Guid> MA_LOAI { get; set; }
        public Nullable<System.Guid> MA_MON { get; set; }
        public Nullable<System.Guid> MA_KHOI { get; set; }
        public string MA_GV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUOI_HOC> BUOI_HOC { get; set; }
        public virtual GIAO_VIEN GIAO_VIEN { get; set; }
        public virtual KHOI_LOP KHOI_LOP { get; set; }
        public virtual LOAI_LOP LOAI_LOP { get; set; }
        public virtual MON_HOC MON_HOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THOI_KHOA_BIEU> THOI_KHOA_BIEU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONG_NO> CONG_NO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOC_SINH> HOC_SINH { get; set; }
    }
}
