//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTam.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGOAI_GIO
    {
        public System.Guid MA_LUONG { get; set; }
        public string MA_GV { get; set; }
        public Nullable<System.DateTime> NGAY_LAM { get; set; }
    
        public virtual BANG_LUONG BANG_LUONG { get; set; }
        public virtual GIAO_VIEN GIAO_VIEN { get; set; }
    }
}
