//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTam.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAI_KHOAN
    {
        public string ID { get; set; }
        public string TEN { get; set; }
        public string MAT_KHAU { get; set; }
        public string CHUC_VU { get; set; }
    
        public virtual GIAO_VIEN GIAO_VIEN { get; set; }
        public virtual HOC_SINH HOC_SINH { get; set; }
    }
}
