//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTam.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAILIEU
    {
        public System.Guid MATL { get; set; }
        public string TENTL { get; set; }
        public string LINK { get; set; }
        public Nullable<System.Guid> MONHOC { get; set; }
        public Nullable<int> KHOI { get; set; }
    
        public virtual MON_HOC MON_HOC { get; set; }
    }
}
