//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTam.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANG_CHU
    {
        public System.DateTime NGAY_AP_DUNG { get; set; }
        public string MUC_TIEU { get; set; }
        public string GIOI_THIEU { get; set; }
        public string DIA_CHI { get; set; }
        public string EMAIL { get; set; }
        public string SDT1 { get; set; }
        public string SDT2 { get; set; }
        public string TIEUDE_MONHOC { get; set; }
    }
}
